server:
  port: 8080

spring:
  application:
    name: gateway-service

cloud:
  gateway:
    routes:

      - id: upi-service
        uri: http://localhost:8081
        predicated:
          -Path=/upi/**
        filters:
          - name: CircuitBreaker
            args:
              name: upiCB
              fallbackUri: forward://fallback/upi

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics


resilience4j:
  circuitbreaker:
    instances:
      upiCB:
        sliding-window-size: 20
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 30s
